name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3'
          cache: 'npm'
          cache-dependency-path: ./package.json

      - name: Install Dependencies
        run: npm install  # Changed from npm ci to npm install

      - name: Build
        run: npm run build

      #- name: Clean Remote Directory
      #  run: |
      #    curl -X DELETE \
      #    --basic \
      #    --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
      #    -L -v \
      #    --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
      #    -f || echo "Directory doesn't exist or already deleted"
#
      #- name: Create Remote Directory
      #  run: |
      #    curl -X MKCOL \
      #    --basic \
      #    --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
      #    -L -v \
      #    --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
      #    -f || echo "Failed to create directory, might already exist"
#
      - name: Deploy Build to WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.WEBDAV_URL }}
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          remote: "/findWordsWithKnownLetters/build"
          local: "build"
      
      - name: Deploy Node_Modules to WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.WEBDAV_URL }}
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          remote: "/findWordsWithKnownLetters/node_modules"
          local: "node_modules"

      - name: Deploy Package.json to WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.WEBDAV_URL }}
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          remote: "/findWordsWithKnownLetters/package.json"
          local: "package.json"
          
      - name: Restart Application
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"method":"restart"}' \
            http://${{ secrets.APP_HOST }}:3001/process/1/action