name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Remote Directory
        run: |
          curl -X DELETE \
          --basic \
          --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
          -L -v \
          --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
          -f || echo "Directory doesn't exist or already deleted"
      - name: Create Remote Directory
        run: |
          curl -X MKCOL \
          --basic \
          --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
          -L -v \
          --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
          -f || echo "Failed to create directory, might already exist"

      - name: Deploy to WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.WEBDAV_URL }}
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          remote: "/findWordsWithKnownLetters"
          local: "."